### ISSUE TITLE
erro no fechamento do css  sidebar-footer

### ISSUE THREAD

**Issue by DocCaio** [alura-cursos/spotify-imersao#4]
faltou fechar  com } alem da medica comparativa incompleta   

```css

.section-playlist__content .subtitle {
    font-weight: 500;
    font-size: 0.8rem; /* 12.

```

dSeixei o meu assim 

```css
.section-playlist__content .subtitle {
    font-weight: 500;
    font-size: 0.8rem; /* 12.px */
    }

```
